<Root>:
    Label:
        font_size: 40
        center_x: root.width / 2
        top: root.top - 10
        text: "PYMODORO"
    Label:
        font_size: 40
        center_x: root.width / 2
        top: root.top - 80
        text: "00:00"
    Button:
    	font_size: 20
    	text: "START"
    	color: (0, 0, 0, 1)
    	background_color: (255, 255, 255, 1)
    	top: root.top - 160
    	center_x: root.width / 2
    	size: 70, 30
